<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flatpickr/4.6.9/flatpickr.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flatpickr/4.6.9/themes/airbnb.min.css">
    <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.js" defer></script>
    <script src="https://cdn.tailwindcss.com"></script>
    <title>Squezze My Task!</title>
</head>
<body>


<!-- formulario edit task-->


<div class="flex justify-center items-center min-h-screen bg-gradient-to-r from-yellow-200 to-purple-300">

    <div class="w-full sm:w-96 bg-white rounded shadow-2xl p-8 m-4">
        
        <h1 class="block w-full font-roboto font-semibold text-center text-gray-700 text-2xl mb-5">Edit Task</h1>
        
        <form action="" method="post">

            <div class="flex flex-col mb-4">
                <label class="mb-2 font-roboto font-semibold text-lg text-gray-700" for="title_task">Title</label>
                <input class="border border-fuchsia-300 py-2 px-3 text-gray-800" type="text" name="title" id="title" required value="<?php echo $this->tasks['title']; ?>">
            </div>

            <div class="flex flex-col mb-4">
                <label class="mb-2 font-roboto font-semibold text-lg text-gray-700" for="textarea">Text</label>
                <textarea class="border border-purple-300 py-2 px-3 text-gray-800" required name="textarea" id="textarea"><?php echo $this->tasks['textarea']; ?></textarea>
            </div>

            <div class="flex flex-col mb-4">
                <label class="mb-2 font-roboto font-semibold text-lg text-gray-700" for="Status">Status</label>
                <select class="border border-violet-300 py-2 px-3 text-grey-500" name="status" id="status">
                <option value="" disabled selected>Select...</option>
                    <option <?php echo ($this->tasks['status'] === 'cc') ? 'selected' : ''; ?>>Pending</option>
                    <option <?php echo ($this->tasks['status'] === 'Running') ? 'selected' : ''; ?>>Running</option>
                    <option <?php echo ($this->tasks['status'] === 'Completed') ? 'selected' : ''; ?>>Completed</option>
                </select>
            </div>

            <!-- Starting date -->
            <div class="flex flex-col mb-4">
                <label for="datetime" class="mb-2 font-roboto font-semibold text-lg text-gray-700">Starting date</label>
                <input name="datetime" type="datetime-local" id="datetime" value="<?php echo $this->tasks['datetime']; ?>" class="border border-indigo-200 py-2 px-3 text-gray-800">
            </div>

            <!-- Closing date -->
            <div class="flex flex-col mb-4">
                <label for="endtime" class="mb-2 font-roboto font-semibold text-lg text-gray-700">Ending date</label>
                <input name="endtime" type="datetime-local" id="endtime" value="<?php echo $this->tasks['endtime']; ?>" class="border border-lime-200 py-2 px-3 text-gray-800">
            </div>

            <div class="flex flex-col mb-4">
                <label class="mb-2 font-roboto font-semibold text-lg text-gray-700" for="user_name">User</label>
                <input class="border border-yellow-300 py-2 px-3 text-gray-800" required value="<?php echo $this->tasks['user']; ?>" type="text" name="user" id="user">
            </div>

            <!---buttons -->

            <div class="flex flex-col sm:flex-row justify-center items-center">
                <a href="index" class="block bg-rose-300 hover:bg-rose-500 text-white font-roboto uppercase text-lg m-2 p-2 px-7 py-2 rounded-md">Back</a>
                <button class="block bg-rose-300 hover:bg-rose-500 font-roboto text-white uppercase text-lg m-2 p-2 px-7 py-2 rounded-md" type="submit">Save changes</button>
            </div>
        </form>
    </div>
</div>

</body>
</html>
