<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>EditTask</title>
</head>
<body>


<!-- formulario edit task-->
<div class="flex justify-center items-center w-full bg-gradient-to-r from-yellow-200 to-purple-300">
    <div class="w-2/5 bg-white rounded shadow-2xl p-8 m-4">
        
    <h1 class="block w-full font-roboto font-semibold text-center text-gray-700 text-2xl mb-5">Edit Task</h1>
        
        <form action="" method="post">

            <div class="flex flex-col mb-4">
                <label class="mb-2 font-roboto font-semibold text-lg text-gray-900" for="title_task">Title</label>
                <input class="border border-fuchsia-300 py-2 px-3 text-gray-800" type="text" name="title" id="title" value="<?php echo $this->tasks['title']; ?>">
            </div>

            <div class="flex flex-col mb-4">
                <label class="mb-2 font-roboto font-semibold text-lg text-gray-900" for="textarea">Text</label>
                <input class="border border-purple-300 py-2 px-3 text-grey-800" value="<?php echo $this->tasks['textarea']?>"name="textarea" id="textarea"></input>
            </div>

            <div class="flex flex-col mb-4">
                <label class="mb-2 font-roboto font-semibold text-lg text-gray-900" for="Status">Status</label>
                <select class="border border-violet-300 py-2 px-3 text-grey-800"> 
                
                <option>Pending</option>                    
                <option>Running</option>
                <option>Completed</option>
                    
                </select>
            </div>

            <div class="flex flex-col mb-4">
                <label class="mb-2 font-roboto font-semibold text-lg text-gray-900" for="Date">Starting Date</label>
                <input class="border border-indigo-300 py-2 px-3 text-grey-800" value="<?php echo $this->tasks['startTime']?>"type="date" name="date" id="date"></input>
            </div>

            <div class="flex flex-col mb-4">
                <label class="mb-2 font-roboto font-semibold text-lg text-gray-900" for="Date">Closing Date</label>
                <input class="border border-lime-300 py-2 px-3 text-grey-800" type="date" name="date" id="date">
            </div>

            <div class="flex flex-col mb-4">
                <label class="mb-2 font-roboto font-semibold text-lg text-gray-900" for="user_name">User</label>
                <input class="border border-yellow-300 py-2 px-3 text-grey-800" value="<?php echo $this->tasks['user']; ?>" type="text" name="user" id="user">
            </div>

            <!---botones -->

            <div class="flex flex-direction-row justify-center items-center">
                <a href="index" class="block bg-rose-300 hover:bg-rose-500 text-white font-roboto uppercase text-lg m-2 p-2 px-7 py-2 rounded-md">Back</a>

                <!--- aqui el controlador redirigirá al index, por eso es un button--->
                
                <button class="block bg-rose-300 hover:bg-rose-500 font-roboto text-white uppercase text-lg m-2 p-2  px-7 py-2 rounded-md" type="submit">Save changes</button>
           </div>
        </form>
    </div>
</div>
</body>
</html>