<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <script src="https://cdn.tailwindcss.com"></script>

    <title>main</title>
</head>
<div id=inicio></div>

<body>

    <!-- page -->
    <main class="min-h-screen w-full bg-gradient-to-r from-yellow-200 to-purple-300 p-2 text-gray-700" x-data="layout">
        <!-- header page -->

        <header class="flex items-center justify-left w-full py-4">
            <div class="text-center font-roboto text-xl font-semibold tracking-wide m-3">Squezze my task</div>
            </div>
        </header>

        <!-- botón añadir task--->

        <div class="flex justify-center m-5 p-5">

            <a href="newTask" class="flex items-center space-x-1 bg-amber-200 rounded-md px-2 py-3 hover:bg-gray-100 hover:text-pink-600">
                <span class="material-symbols-outlined">add</span>
                <span>New task</span>
            </a>

        </div>
        <!-- aside

        <aside class="flex w-60 flex-col space-y-5 border-r-2 bg-white" style="height: 90.5vh"
            x-show="asideOpen">
                
            <---botones menu lateral -->

        <!-- <a href="#" class="flex items-center space-x-1 rounded-md px-2 py-5 hover:bg-gray-100 hover:text-blue-600">
                <span class="text-2xl"><i class="bx bx-home"></i></span>
                <span>My tasks</span>
            </a>

            <a href="#" class="flex items-center space-x-1 rounded-md px-2 py-3 hover:bg-gray-100 hover:text-blue-600">
                <span class="material-symbols-outlined">add</span>
                <span>New task</span>
            </a>

        </aside> -->

        <!-- main content page -->

        <!-- tabla de tasks -->

        <div class="flex justify-center">

            <table class="w-5/6 rounded-lg">

                <!-- Fila encabezados-->
                <thead>
                    <tr>
                        <th class="p-3 font-bold uppercase bg-fuchsia-200 text-gray-600 border border-gray-300 hidden lg:table-cell">Title</th>
                        <th class="p-3 font-bold uppercase bg-purple-200 text-gray-600 border border-gray-300 hidden lg:table-cell">Text</th>
                        <th class="p-3 font-bold uppercase bg-violet-200 text-gray-600 border border-gray-300 hidden lg:table-cell">Status</th>
                        <th class="p-3 font-bold uppercase bg-indigo-100 text-gray-600 border border-gray-300 hidden lg:table-cell">Starting date</th>
                        <th class="p-3 font-bold uppercase bg-lime-200 text-gray-600 border border-gray-300 hidden lg:table-cell">Ending date</th>
                        <th class="p-3 font-bold uppercase bg-yellow-200 text-gray-600 border border-gray-300 hidden lg:table-cell">User</th>
                        <th class="p-3 font-bold uppercase bg-amber-200 text-gray-600 border border-gray-300 hidden lg:table-cell">Show</th>
                        <th class="p-3 font-bold uppercase bg-amber-200 text-gray-600 border border-gray-300 hidden lg:table-cell">Edit</th>
                        <th class="p-3 font-bold uppercase bg-amber-200 text-gray-600 border border-gray-300 hidden lg:table-cell">Delete</th>
                    </tr>
                </thead>

                <tbody>
                    <!-- TASK 1 EJEMPLO -->
                    <?php foreach ($this->tasks as $task) : ?>
                        <tr class="odd:bg-white even:bg-stone-50 bg-white lg:hover:bg-gray-100 flex lg:table-row flex-row lg:flex-row flex-wrap lg:flex-no-wrap mb-4">
                            <td class="w-full lg:w-auto p-3 text-gray-800 text-center border border-b block lg:table-cell relative lg:static">
                                <?php echo $task['title']; ?>
                            </td>
                            <td class="w-full lg:w-auto p-3 text-gray-800 text-center border border-b text-center block lg:table-cell relative lg:static">
                                <?php echo $task['textarea']; ?>
                            </td>
                            <td class="w-full lg:w-auto p-3 text-gray-800 text-center border border-b text-center block lg:table-cell relative lg:static">
                                <span class="rounded bg-green-400 py-1 px-3 text-xs font-bold">
                                <?php echo $task['status']; ?>
                                </span>
                            </td>
                            <td class="w-full lg:w-auto p-3 text-gray-800 text-center border border-b text-center block lg:table-cell relative lg:static"><?php echo $task['datetime']; ?></td>
                            <td class="w-full lg:w-auto p-3 text-gray-800 text-center border border-b text-center block lg:table-cell relative lg:static"><?php echo $task['endtime']; if(empty($task['endtime'])){ echo " - ";}; ?></td>
                            <td class="w-full lg:w-auto p-3 text-gray-800 text-center border border-b text-center block lg:table-cell relative lg:static">
                                <?php echo $task['user']; ?></td>
                            <td class="w-full lg:w-auto p-3 text-gray-800 text-center border border-b   block lg:table-cell relative lg:static">
                                <a href="show?id=<?php echo $task['id']; ?>" class="text-blue-400 hover:text-blue-600 underline pl-6"><span class="material-symbols-outlined bg-">
                                        visibility
                                    </span></a>
                            </td>
                            <td class="w-full lg:w-auto p-3 text-gray-800 text-center border border-b text-center block lg:table-cell relative lg:static">
                                <a href="edit?id=<?php echo $task['id']; ?>" class="text-blue-400 hover:text-blue-600 underline pl-6">Edit</a>
                            </td>
                            <td class="w-full lg:w-auto p-3 text-gray-800 text-center border border-b text-center block lg:table-cell relative lg:static">
                                <a href="delete?id=<?php echo $task['id']; ?>"  onclick="return confirm('Are you sure you want to delete this task?')" class="text-blue-400 hover:text-blue-600 underline pl-6">Delete</a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </main>
</body>

</html>