<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Squezze My Task!</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.15/dist/tailwind.min.css" rel="stylesheet">
</head>
<body>
   
    <div class="h-screen bg-gradient-to-r from-yellow-300 to-purple-400 flex items-center">
        <section class="w-full bg-cover bg-center py-10 sm:py-20 md:py-32">
            <div class="container mx-auto text-center text-white">
                

                 <h1 class="font-roboto md:text-7xl font-semibold tracking-wide mb-6 whitespace-normal md:flex md:flex-col md:items-center sm:text-7xl text-5xl">
                    SQUEZZE <br class="md:hidden"> MY TASK
                </h1>
                <p class="font-roboto text-2xl m-6 md:m-10">Make my task easy</p>
                
            
            
            <a href="index">
                <button class="bg-yellow-300 hover:bg-purple-400 mt-4 p-4 rounded-full w-1/6 text-white font-roboto font-semibold text-xl">
                            Start
                        </button>
                    </a>
            </div>
        </section>
    </div>
</body>
</html>
