<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>landingPage</title>
</head>
<body>
    <!-- component -->
<div class="h-screen bg-gradient-to-r from-yellow-300 to-purple-400 flex items-center">
	<section class="w-full bg-cover bg-center py-32">
		<div class="container mx-auto text-center text-white">
			
			<h1 class="font-roboto text-7xl font-semibold tracking-wide mb-10">SQUEZZE MY TASK</h1>
			<p class="font-roboto text-xl m-10">Make my task easy</p>
			
			<a href="index" class="text-white font-bold bg-yellow-300  py-4 px-12 rounded-full hover:bg-lime-300">Start</a>

		</div>
	</section
</div>
</body>
</html>

