<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flatpickr/4.6.9/flatpickr.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flatpickr/4.6.9/themes/airbnb.min.css">
    <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.js" defer></script>
    <title>Squezze My Task!</title>
    
</head>
<body>




<div class="flex justify-center items-center w-full bg-gradient-to-r from-yellow-200 to-purple-300">
    
    <div class="w-2/5 max-sm:w-full max-md:w-2/3 max-lg:w-1/2 bg-white rounded shadow-2xl p-8 m-4">
        
    <h1 class="w-full font-roboto font-semibold text-center text-gray-700 text-2xl mb-5">New Task</h1>
        
        <form action="" method="post">

            <div class="flex flex-col mb-4 sm-w-1/2">
                <label class="mb-2 font-roboto font-semibold text-lg text-gray-700" for="title_task">Title</label>
                <input class="border border-fuchsia-300 py-2 px-3 text-gray-800" type="text" name="title" id="title" maxlength="20" placeholder="Max 20 characters" required>
            </div>
            
            <div class="flex flex-col mb-4">
                <label class="mb-2 font-roboto font-semibold text-lg text-gray-700" for="textarea">Text</label>
                <textarea class="border border-purple-300 py-2 px-3 text-grey-800" name="textarea" id="textarea" maxlength="120" placeholder="Max 120 characters" required></textarea>
            </div>

            <div class="flex flex-col mb-4">
                <label class="mb-2 font-roboto font-semibold text-lg text-gray-700" for="status">Status</label>
                <select class="border border-violet-300 py-2 px-3 text-gray-500" name="status" required>
                    <option value= "" disabled selected>Select...</option>
                    <option value="Pending">Pending</option>
                    <option value="Running">Running</option>
                    <option value="Completed">Completed</option>
                </select>
            </div>
        <!-- Starting date -->
            <div
                x-data
                x-init="flatpickr($refs.datetimewidget, {wrap: true, enableTime: true, dateFormat: 'M j, Y h:i K', minDate: 'today'});"
                x-ref="datetimewidget"
                name="datetime"
                class="flex flex-col flatpickr container mx-auto col-span-6 sm:col-span-6 mt-5 mb-5">
                <label for="datetime" class="flex-grow block mb-2 font-roboto font-semibold text-lg text-gray-700">Starting date</label>
                <div class="flex align-middle align-content-center border border-indigo-200">
                    <input
                        x-ref="datetime"
                        name="datetime"
                        type="text"
                        id="datetime"
                        
                        data-input
                        
                        placeholder="Select.."
                        class="block w-full px-2 focus:border-lime-300 focus:ring focus:ring-teal-200 focus:ring-opacity-50 rounded-l-md"
                        min="datetime-local">
                    <a class="h-11 w-10 input-button cursor-pointer rounded-r-md bg-transparent "
                        title="clear" data-clear>
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-7 w-7 mt-2 ml-1" viewBox="0 0 20 20" fill="#94ADD7">
                            <path fill-rule="evenodd"
                                d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
                                clip-rule="evenodd"/>
                        </svg>
                    </a>
                </div>
            </div>
<!--Closing date -->
            <div
                x-data
                x-init="flatpickr($refs.datetimewidget, {wrap: true, enableTime: true, dateFormat: 'M j, Y h:i K'});"
                x-ref="datetimewidget"
                name="endtime"
                class="flex flex-col flatpickr container mx-auto col-span-6 sm:col-span-6 mt-5 mb-5">
                <label for="datetime" class="flex-grow block mb-2 font-roboto font-semibold text-lg text-gray-700">Ending date</label>
                <div class="flex align-middle align-content-center border border-lime-200">
                    <input
                        x-ref="endtime"
                        name="endtime"
                        type="text"
                        id="endtime"
                        data-input
                        placeholder="Select.."
                        class="block w-full px-2 focus:border-lime-300 focus:ring focus:ring-teal-200 focus:ring-opacity-50 rounded-l-md">
                        
                    <a class="h-11 w-10 input-button cursor-pointer rounded-r-md bg-transparent "
                        title="clear" data-clear>
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-7 w-7 mt-2 ml-1" viewBox="0 0 20 20" fill="#BDF741">
                            <path fill-rule="evenodd"
                                d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
                                clip-rule="evenodd"/>
                        </svg>
                    </a>
                </div>
            </div>
            <div class="flex flex-col mb-4">
                <label class="mb-2 font-roboto font-semibold text-lg text-gray-700" for="user_name">User</label>
                <input class="border border-yellow-300 py-2 px-3 text-grey-800" type="text" name="user" id="user" maxlength="20" placeholder="Max 20 characters" required>
            </div>
            
            <button class="block bg-rose-300 hover:bg-rose-500 mt-7 text-white uppercase text-lg mx-auto p-3 rounded-full" type="submit">Save task</button>
        </form>
    </div>
</div>
</body>
</html>