<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Angkor&display=swap" rel="stylesheet">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>landingPage</title>
</head>
<body>
    <!-- component -->
<div class="h-screen bg-gradient-to-r from-emerald-700 to-emerald-600 flex items-center">
	<section class="w-full bg-cover bg-center py-32">
		<div class="container mx-auto text-center text-white">
			<h1 class="font-angkor text-5xl mb-6">SQUEZZE MY TASK</h1>
			<p class="font-angkor text-xl mb-12">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio,
				gravida pellentesque urna varius vitae.</p>
			<a href="#" class="bg-indigo-500 text-white py-4 px-12 rounded-full hover:bg-indigo-600">Start</a>
		</div>
	</section>
</div>
</body>
</html>