<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>Squezze My Task!</title>
</head>
<body>

<!-- delete form -->
<div class="bg-gradient-to-r from-yellow-300 to-purple-400 bg-opacity-50 flex justify-center items-center absolute top-0 right-0 bottom-0 left-0">
  <div class="bg-white px-20 py-20 rounded-md text-center">
    <h1 class="text-xl mb-4 font-roboto font-semibold text-slate-700">Delete task</h1>
    <p class="text-base mb-9 font-roboto font-semibold text-slate-500">Are you sure?</p>

    <button class="bg-lime-300 hover:bg-lime-400 px-7 py-2 ml-2 rounded-md font-roboto font-semibold text-md text-white">Yes</button>
    <button class="bg-rose-300 hover:bg-rose-400 px-7 py-2 ml-2 rounded-md font-roboto font-semibold text-md text-white">No</button>
    
  </div>
</div>
</body>
</html>