<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Angkor&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Oswald:wght@200;300;500&display=swap" rel="stylesheet">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>EditTask</title>
</head>
<body>


<!-- formulario -->
<div class="flex justify-center items-center w-full bg-gradient-to-r from-emerald-700 to-emerald-600">
    <div class="w-1/2 bg-white rounded shadow-2xl p-8 m-4">
        <h1 class="block w-full text-center text-gray-800 text-2xl font-bold mb-6">New Task</h1>
        <form action="/" method="post">

            <div class="flex flex-col mb-4">
                <label class="mb-2 font-bold text-lg text-gray-900" for="first_name">Title</label>
                <input class="border py-2 px-3 text-grey-800" type="text" name="title" id="title">
            </div>
            <div class="flex flex-col mb-4">
                <label class="mb-2 font-bold text-lg text-gray-900" for="email">User</label>
                <input class="border py-2 px-3 text-grey-800" type="email" name="email" id="email">
            </div>
            
            <div class="flex flex-col mb-4">
                <label class="mb-2 font-bold text-lg text-gray-900" for="Date">Date</label>
                <input class="border py-2 px-3 text-grey-800" type="date" name="date" id="date">
            </div>
            
             <div class="flex flex-col mb-4">
                <label class="mb-2 font-bold text-lg text-gray-900" for="textarea">textarea</label>
                <textarea class="border py-2 px-3 text-grey-800" name="textarea" id="textarea"></textarea>
            </div>

            <div class="flex flex-col mb-4">
                <label class="mb-2 font-bold text-lg text-gray-900" for="Status">Status</label>
                <select class="border py-2 px-3 text-grey-800">
                    <option>Pending</option>
                    <option>Running</option>
                    <option>Completed</option>
                </select>
            </div>
            <button class="block bg-green-400 hover:bg-green-600 text-white uppercase text-lg mx-auto p-4 rounded" type="submit">Save</button>
        </form>
    </div>
</div>
</body>
</html>