
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>Squezze My Task!</title>
</head>
<body>

<body>

    <!-- page -->
    <main class="min-h-screen w-full bg-gradient-to-r from-yellow-200 to-purple-300 p-2 text-gray-700" x-data="layout">
        <!-- header page -->

        <header class="flex items-center justify-left w-full py-4">
                <div class= "text-center font-roboto text-xl font-semibold tracking-wide m-3">Squezze my task</div>
            </div>
        </header>

    <!-- botón añadir task--->

        <div class= "flex justify-center m-5 p-5">
            
            <a href="newTask.phtml"class="flex items-center space-x-1 rounded-md px-2 py-3 hover:bg-gray-100 hover:text-pink-600">
                <span class="material-symbols-outlined">add</span>
                <span>New task</span>
            </a>

        </div>
        <!-- aside

        <aside class="flex w-60 flex-col space-y-5 border-r-2 bg-white" style="height: 90.5vh"
            x-show="asideOpen">
                
            <---botones menu lateral -->

            <!-- <a href="#" class="flex items-center space-x-1 rounded-md px-2 py-5 hover:bg-gray-100 hover:text-blue-600">
                <span class="text-2xl"><i class="bx bx-home"></i></span>
                <span>My tasks</span>
            </a>

            <a href="#" class="flex items-center space-x-1 rounded-md px-2 py-3 hover:bg-gray-100 hover:text-blue-600">
                <span class="material-symbols-outlined">add</span>
                <span>New task</span>
            </a>

        </aside> --> 

        <!-- main content page -->
        
          <!-- tabla de tasks -->
        
    <div class="flex justify-center">
            
        <table class="w-5/6 rounded-lg">   
        
            <!-- Fila encabezados-->
            <thead>
                <tr>
                <th class="p-3 font-bold uppercase bg-fuchsia-200 text-gray-600 border border-gray-300 hidden lg:table-cell">Title</th>
                <th class="p-3 font-bold uppercase bg-purple-200 text-gray-600 border border-gray-300 hidden lg:table-cell">Text</th>
                <th class="p-3 font-bold uppercase bg-violet-200 text-gray-600 border border-gray-300 hidden lg:table-cell">Status</th>
                <th class="p-3 font-bold uppercase bg-indigo-100 text-gray-600 border border-gray-300 hidden lg:table-cell">Starting date</th>
                <th class="p-3 font-bold uppercase bg-lime-200 text-gray-600 border border-gray-300 hidden lg:table-cell">Closing date</th>
                <th class="p-3 font-bold uppercase bg-yellow-200 text-gray-600 border border-gray-300 hidden lg:table-cell">User</th>
                <th class="p-3 font-bold uppercase bg-amber-200 text-gray-600 border border-gray-300 hidden lg:table-cell">Actions</th>
                </tr>
            </thead>

            <tbody>
                <!-- TASK 1 EJEMPLO -->
                
                <tr class="bg-white lg:hover:bg-gray-100 flex lg:table-row flex-row lg:flex-row flex-wrap lg:flex-no-wrap mb-4">
                    <td class="w-full lg:w-auto p-3 text-gray-800 text-center border border-b block lg:table-cell relative lg:static">Medical appointment</td>
                    <td class="w-full lg:w-auto p-3 text-gray-800 text-center border border-b text-center block lg:table-cell relative lg:static">Dr. Sheridan, Reumatologist</td>
                    <td class="w-full lg:w-auto p-3 text-gray-800 text-center border border-b text-center block lg:table-cell relative lg:static">
                        <span class="rounded bg-green-400 py-1 px-3 text-xs font-bold">done</span>
                    </td>
                    <td class="w-full lg:w-auto p-3 text-gray-800 text-center border border-b text-center block lg:table-cell relative lg:static">22-07-23</td>
                    <td class="w-full lg:w-auto p-3 text-gray-800 text-center border border-b text-center block lg:table-cell relative lg:static">25-07-23</td>
                    <td class="w-full lg:w-auto p-3 text-gray-800 text-center border border-b text-center block lg:table-cell relative lg:static">Elisia Me</td>
                    <td class="w-full lg:w-auto p-3 text-gray-800 text-center border border-b text-center block lg:table-cell relative lg:static">
                        <a href="showTask.phtml" class="text-blue-400 hover:text-blue-600 underline pl-6">Show</a>
                        <a href="editTask.phtml" class="text-blue-400 hover:text-blue-600 underline pl-6">Edit</a>
                        <a href="deleteTask.phtml" class="text-blue-400 hover:text-blue-600 underline pl-6">Remove</a>
                        </td>
                </tr>
            </tbody>
        </table>
    </div>
</main>
</body>

</html>