<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>Squezze My Task!</title>
    
</head>
<body>


<!-- formulario -->

<div class="flex justify-center items-center w-full bg-gradient-to-r from-yellow-200 to-purple-300">
    <div class="w-2/5 bg-white rounded shadow-2xl p-8 m-4">
        
    <h1 class="block w-full font-roboto font-semibold text-center text-gray-700 text-2xl mb-5">New Task</h1>
        
        <form action="" method="POST">

            <div class="flex flex-col mb-4">
                <label class="mb-2 font-roboto font-semibold text-lg text-gray-900" for="title_task">Title</label>
                <input class="border border-fuchsia-300 py-2 px-3 text-gray-800" type="text" name="title" id="title">
            </div>

            <div class="flex flex-col mb-4">
                <label class="mb-2 font-roboto font-semibold text-lg text-gray-900" for="textarea">Text</label>
                <textarea class="border border-purple-300 py-2 px-3 text-grey-800" name="textarea" id="textarea"></textarea>
            </div>

            <div class="flex flex-col mb-4">
                <label class="mb-2 font-roboto font-semibold text-lg text-gray-900" for="Status">Status</label>
                <select class="border border-violet-300 py-2 px-3 text-grey-800">
                    <option>Pending</option>
                    <option>Running</option>
                    <option>Completed</option>
                </select>
            </div>
            <!-- seleccionar hora -->
            <div class = flex flex-col mb-4>
            <!-- component -->
            <label class="mb-2 font-roboto font-semibold text-lg text-gray-900" for="Start">Starting Time</label>
                <div class="mt-5 p-5 mb-5 w-40 bg-white rounded-lg">
                <div class="flex">
                    <select name="hours" class="bg-transparent text-xl appearance-none">
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                    <option value="6">6</option>
                    <option value="7">7</option>
                    <option value="8">8</option>
                    <option value="9">9</option>
                    <option value="10">10</option>
                    <option value="11">10</option>
                    <option value="12">12</option>
                    </select>
                    <span class="text-xl mr-3">:</span>
                    <select name="minutes" class="bg-transparent text-xl appearance-none outline-none mr-4">
                    <option value="0">00</option>
                    <option value="30">30</option>
                    </select>
                    <select name="ampm" class="bg-transparent text-xl appearance-none outline-none">
                    <option value="am">AM</option>
                    <option value="pm">PM</option>
                    </select>
                </div>
                </div>
            </div>
            <div class="flex flex-col mb-4">
                <label class="mb-2 font-roboto font-semibold text-lg text-gray-900" for="user_name">User</label>
                <input class="border border-yellow-300 py-2 px-3 text-grey-800" type="text" name="user" id="user">
            </div>
            
            <button class="block bg-rose-300 hover:bg-rose-500 text-white uppercase text-lg mx-auto p-2 rounded" type="submit">Save task</button>
        </form>
    </div>
</div>
</body>
</html>