<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Angkor&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Oswald:wght@200;300;500&display=swap" rel="stylesheet">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>showTask</title>
</head>
<body>

<!-- component -->

<div class='flex items-center justify-center min-h-screen from-pink-200 via-purple-300 to-blue-500 bg-gradient-to-br'>

    <div class='w-full max-w-lg py-8 flex flex-row items-center justify-center mx-auto bg-[#FFFBFB] rounded-lg shadow-xl'>

        <div class="flex flex-col md:flex-row w-3/4 md:w-5/6 space-x-0 md:space-x-8">
          
            <div class="w-full md:w-2/5 flex flex-col items-center justify-center">
                
            </div>
            <div class="w-full md:w-3/5 space-y-4 flex flex-col justify-center items-center">
                <div class="flex flex-col justify-center">
                    <h1 class="text-center md:text-left text-2xl font-bold text-gray-900">Title of my task</h1>
                    <p class="inline text-gray-700 font-normal leading-6 w-full text-base">User name</p>
                    <p class="inline text-gray-700 font-normal leading-6 w-full text-base">Date time</p>
                    <p class="inline text-gray-700 font-normal leading-6 w-full text-base">Lorem ipsum dolor sit amet consectetur adipisicing elit. Et in, saepe, hic, quod ipsum fugiat obcaecati est delectus veritatis minima numquam beatae eum alias deleniti possimus impedit dolorum voluptatum quae!</p>
                </div>
                
                <button class="transition-colors bg-purple-700 hover:bg-purple-800 p-1 rounded-sm w-full text-white text-hover shadow-md shadow-purple-900">
                    Follow
                </button>
            </div>
        </div>
    </div>
</div>
</body>
</html>