<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"/>
    <link href="https://fonts.googleapis.com/css2?family=Angkor&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Oswald:wght@200;300;500&display=swap" rel="stylesheet">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>main</title>
</head>
<body>
<!-- component -->


    <!-- page -->
    <main class="min-h-screen w-full bg-gradient-to-r from-emerald-400 to-teal-300 p-2 text-gray-700" x-data="layout">
        <!-- header page -->
        <header class="flex w-full items-center justify-between border-b-2 border-gray-200 bg-white p-2">
            <!-- logo limon -->
            <div class="flex items-center space-x-10">
                
                <div style= "font-family:'Angkor', cursive; font-size: 18pt; margin-left:10px; ">Squezze my task</div>


            </div>

            
            
        
        </header>

        <div class="flex">
            <!-- aside -->
            <aside class="flex w-72 flex-col space-y-5 border-r-2 border-blue-200 bg-white" style="height: 90.5vh"
                x-show="asideOpen">
                <!--botones menu lateral -->

                <a href="#" class="flex items-center space-x-1 rounded-md px-2 py-5 hover:bg-gray-100 hover:text-blue-600">
                    <span class="text-2xl"><i class="bx bx-home"></i></span>
                    <span>My tasks</span>
                </a>

                <a href="#" class="flex items-center space-x-1 rounded-md px-2 py-3 hover:bg-gray-100 hover:text-blue-600">
                    <span class="material-symbols-outlined">add</span>
                    <span>New task</span>
                </a>

                <a href="#" class="flex items-center space-x-1 rounded-md px-2 py-3 hover:bg-gray-100 hover:text-blue-600">
                    <span class="material-symbols-outlined">edit_note</span>
                    <span>Modify</span>
                </a>

                <a href="#" class="flex items-center space-x-1 rounded-md px-2 py-3 hover:bg-gray-100 hover:text-blue-600">
                    <span class="material-symbols-outlined">file_open</span>
                    <span>Show selected</span>
                </a>

                <a href="#" class="flex items-center space-x-1 rounded-md px-2 py-3 hover:bg-gray-100 hover:text-blue-600">
                <span class="material-symbols-outlined">checklist</span>
                    <span>Show all</span>
                </a>

                <a href="#" class="flex items-center space-x-1 rounded-md px-2 py-3 hover:bg-gray-100 hover:text-blue-600">
                <span class="material-symbols-outlined">delete</span>
                    <span>Delete</span>
                </a>
            </aside>

            <!-- main content page -->
            <div>
                
            </div>
        </div>
    </main>
</body>
